apiVersion: v2
name: key-migration-utility
description: A Helm chart to migrate keys from any keystore type to any other supported format.
type: application
version: 1.3.0-beta.2
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - key-migration-utility
maintainers:
  - email: info@mosip.io
    name: MOSIP
